# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    akabot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

akabot_arm_controller:
  ros__parameters:
    joints:
      - top_plate_joint
      - lower_arm_joint
      - upper_arm_joint
      - wrist_joint      # Corrected to match URDF
      - claw_base_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

hand_controller:
  ros__parameters:
    joint: right_claw_joint
